spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true        # SQL을 포맷하여 보기 좋게 출력
        use_sql_comments: true  # SQL에 주석을 추가하여, 쿼리의 의미를 더 명확히 함
        generate_statistics: true


aws:
  secrets-manager:
    secret-name: myapp/aquila

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org:
      hibernate: debug
      springframework:
        security: debug




