server:
  port: 8080

spring:
  application:
    name: sb-gradle-querydsl
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 활성화
      max-file-size: 2048MB  # 단일 파일 최대 크기
      max-request-size: 2048MB  # 전체 요청 본문 크기 (여러 파일을 포함한 크기)
  datasource:
    url: jdbc:postgresql://192.168.64.5:5432/costco_data  #utm devian
#    url: jdbc:postgresql://localhost:5432/costco_data
    username: joey
    password: EmaEma*#7531
    hikari:
      jdbc-url: jdbc:postgresql://192.168.64.5:5432/costco_data #utm devian
#      jdbc-url: jdbc:postgresql://localhost:5432/costco_data
      username: joey
      password: EmaEma*#7531
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

springdoc:
  swagger-ui:
    path: /swagger-ui  # Swagger UI 접근 경로
    tags-sorter: none
  #    operations-sorter: method
  api-docs:
    path: /api-docs   # Swagger JSON API 문서 경로
